import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { getFirestore,collection,getDocs,query,where } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
const firebaseConfig={apiKey:'AIzaSyDlbk24PnijEVCYQS_3fe26SF_WTC7t_S0',authDomain:'ed-fitness-1398d.firebaseapp.com',projectId:'ed-fitness-1398d',storageBucket:'ed-fitness-1398d.firebasestorage.app',messagingSenderId:'22921993850',appId:'1:22921993850:web:d45223dc43dedc1a8f65c3',measurementId:'G-CFB0BV3XF0'};
const db=getFirestore(initializeApp(firebaseConfig));
const meta={tops:['Tops','Tops fitness para treino e rotina.'],leggings:['Leggings','Leggings fitness com conforto e performance.'],blusas:['Blusas','Blusas e camisetas para treino e lifestyle.'],acessorios:['Acessórios','Acessórios para acompanhar sua rotina fitness.'],macacoes_conjuntos:['Macacões & Conjuntos','Macacões e conjuntos fitness para todos os momentos.'],tenis:['Tênis','Tênis para treino e rotina.'],suplementos:['Suplementos','Suplementos para complementar sua rotina.']};
const normalize=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/&/g,'_').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const key=normalize(new URLSearchParams(location.search).get('categoria')||'tops');
const [title,desc]=meta[key]||['Produtos','Confira nossos produtos.']; document.title=`${title} | ED Fitness`; document.getElementById('pageTitle').textContent=title; document.getElementById('pageDescription').textContent=desc;
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); let cart=JSON.parse(localStorage.getItem('edfitness-cart')||'[]');
function count(){document.getElementById('categoryCartCount').textContent=cart.reduce((s,i)=>s+(Number(i.qty)||1),0)} count();
function toast(t){const el=document.getElementById('categoryToast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1600)}
function add(p){const price=Number(p.promotionalPrice)>0?Number(p.promotionalPrice):Number(p.price)||0;const e=cart.find(i=>i.name===p.name);if(e)e.qty+=1;else cart.push({name:p.name,qty:1,price});localStorage.setItem('edfitness-cart',JSON.stringify(cart));count();toast(`${p.name} adicionado ao carrinho`)}
function render(list){const grid=document.getElementById('categoryGrid');document.getElementById('productCount').textContent=`${list.length} produto${list.length===1?'':'s'}`;if(!list.length){grid.innerHTML='<div class="empty"><strong>Nenhum produto publicado nesta categoria ainda.</strong><br>Verifique o campo category e active no Firebase.</div>';return}grid.innerHTML=list.map((p,i)=>{const price=Number(p.promotionalPrice)>0?Number(p.promotionalPrice):Number(p.price)||0;const gallery=Array.isArray(p.images)&&p.images.length?p.images.filter(Boolean):(p.image?[p.image]:[]);const img=gallery[0]||'';return `<article class="product-card">${img?`<img src="${img}" alt="${p.name}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'"><div class="image-error" style="display:none;aspect-ratio:4/5;align-items:center;justify-content:center;padding:20px;background:#eceee5;text-align:center">Imagem indisponível</div>`:'<div style="aspect-ratio:4/5;background:#eceee5"></div>'}<div class="product-info"><h3>${p.name}</h3><div>${Number(p.promotionalPrice)>0?`<span class="old-price">${money(p.price)}</span>`:''}<span class="price">${money(price)}</span></div>${gallery.length>1?`<small>${gallery.length} fotos</small>`:''}<button data-i="${i}">Adicionar ao carrinho</button></div></article>`}).join('');grid.querySelectorAll('button[data-i]').forEach(b=>b.onclick=()=>add(list[Number(b.dataset.i)]))}
try{console.info('[ED Fitness] Buscando produtos ativos no Firestore...');const snap=await getDocs(query(collection(db,'products'),where('active','==',true)));const all=snap.docs.map(d=>({id:d.id,...d.data()}));console.info('[ED Fitness] Produtos ativos recebidos:',all);const list=all.filter(p=>normalize(p.category)===key);render(list)}catch(e){console.error('[ED Fitness] Falha ao ler Firestore:',e);document.getElementById('productCount').textContent='Erro de conexão';document.getElementById('categoryGrid').innerHTML=`<div class="empty"><strong>Não foi possível carregar o catálogo.</strong><br><small>${String(e.code||e.message||e)}</small></div>`}
document.getElementById('categoryCart').onclick=()=>location.href='index.html#produtos';